#!/usr/bin/env node

// This script simply runs `$ node node_modules/mocha/bin/mocha.js ... params ...`
// mocha script for test files `**/*.spec.js` for the package that called this script from.
// Note-1: test files must be generated by `tsc_tests` bazel rule since execution happens
// during Bazel test phase in runtime.
//
// When `bazel coverage` sets COVERAGE_DIR, Mocha is wrapped with c8 to print a text
// summary (like Vitest) and write LCOV to COVERAGE_OUTPUT_FILE.

import 'mocha';
import 'dotenv';
import 'source-map-support';

import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { exit } from 'node:process';
import { fileURLToPath } from 'node:url';

const DEFAULT_EXIT_CODE = -1;
const DEFAULT_TIMEOUT = 50000;
const DEFAULT_FILES = './dist/**/*.spec.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const _mocha_bin = path.join(__dirname, '../node_modules/mocha/bin/mocha.js');
const _c8_bin = path.join(__dirname, '../node_modules/c8/bin/c8.js');

function getPackageDir() {
  // Prefer rules_js runfiles paths; fall back to legacy argv-based resolution.
  const runfiles = process.env.JS_BINARY__RUNFILES || process.env.RUNFILES;
  const workspace =
    process.env.JS_BINARY__WORKSPACE || process.env.TEST_WORKSPACE || '_main';
  const pkg = process.env.JS_BINARY__PACKAGE || process.env.BAZEL_PACKAGE;
  if (runfiles && pkg) {
    return path.join(runfiles, workspace, pkg);
  }
  return path.join(process.argv[0], '../../');
}

function getMochaArgs() {
  return [
    '--require',
    path.join(__dirname, '../node_modules/dotenv/config'),
    '--require',
    path.join(__dirname, '../node_modules/source-map-support/register'),
    '--grep',
    '.',
    '--timeout',
    String(DEFAULT_TIMEOUT),
    '--exit',
    '--check-leaks',
    '--no-warnings',
    '--fail-zero',
    DEFAULT_FILES,
  ];
}

function getCoverageInclude() {
  return ['dist/**/*.js'];
}

function getCoverageExclude() {
  return [
    'dist/**/*.spec.js',
    '**/*.spec.ts',
    '**/*.spec.js',
    '**/*.test.ts',
    '**/*.test.js',
  ];
}

function prefixLcovPaths(lcovFile, packagePrefix) {
  if (!packagePrefix) {
    return;
  }

  const content = fs.readFileSync(lcovFile, 'utf8');
  const prefixed = content.replace(/^SF:(?!\/)/gm, `SF:${packagePrefix}/`);
  fs.writeFileSync(lcovFile, prefixed);
}

async function runCommand(command, args, env, cwd) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, env, stdio: 'inherit' });

    child.on('close', (code) => resolve(code));
    child.on('error', (err) => reject(err));
  });
}

async function runMochaTests() {
  let exitCode = DEFAULT_EXIT_CODE;
  const _package_dir = getPackageDir();
  const mochaArgs = getMochaArgs();
  const nodeBin = process.execPath;

  try {
    if (process.env.COVERAGE_DIR && process.env.COVERAGE_OUTPUT_FILE) {
      const reportsDir = path.dirname(process.env.COVERAGE_OUTPUT_FILE);
      const include = getCoverageInclude();
      const exclude = getCoverageExclude();
      const env = { ...process.env };
      // c8 manages its own V8 coverage; avoid double-collection from rules_js.
      delete env.NODE_V8_COVERAGE;

      const c8Args = [
        _c8_bin,
        '--reporter=text',
        '--reporter=lcovonly',
        `--reports-dir=${reportsDir}`,
        '--all',
        `--src=${_package_dir}`,
        '--exclude=' + exclude.join(','),
        ...include.flatMap((pattern) => ['--include', pattern]),
        '--',
        nodeBin,
        _mocha_bin,
        ...mochaArgs,
      ];

      exitCode = await runCommand(nodeBin, c8Args, env, _package_dir);

      const lcovInfo = path.join(reportsDir, 'lcov.info');
      if (fs.existsSync(lcovInfo)) {
        fs.renameSync(lcovInfo, process.env.COVERAGE_OUTPUT_FILE);
        prefixLcovPaths(
          process.env.COVERAGE_OUTPUT_FILE,
          process.env.BAZEL_PACKAGE
        );
      }

      return exitCode;
    }

    // The command will look like this:
    // 'node /private/var/tmp/_bazel_tomsoir/828ce2621fc2cfba90cf9c567be84b76/sandbox/darwin-sandbox/811
    // /execroot/_main/bazel-out/darwin_x86_64-fastbuild/bin/experimental/service_test_ts_webpack_react_tests
    // /test_/test.runfiles/_main/tools/test-mocha/scripts/../node_modules/mocha/bin/mocha.js
    // --require /private/var/tmp/_bazel_tomsoir/828ce2621fc2cfba90cf9c567be84b76/sandbox/darwin-sandbox/811/execroot/_main/bazel-out/darwin_x86_64-fastbuild/bin/experimental/service_test_ts_webpack_react_tests/test_/test.runfiles/_main/tools/test-mocha/scripts/../node_modules/dotenv/config
    // --require /private/var/tmp/_bazel_tomsoir/828ce2621fc2cfba90cf9c567be84b76/sandbox/darwin-sandbox/811/execroot/_main/bazel-out/darwin_x86_64-fastbuild/bin/experimental/service_test_ts_webpack_react_tests/test_/test.runfiles/_main/tools/test-mocha/scripts/../node_modules/source-map-support/register
    // --grep .
    // --timeout "50000"
    // --exit
    // --check-leaks
    // --no-warnings
    // --fail-zero
    // /private/var/tmp/_bazel_tomsoir/828ce2621fc2cfba90cf9c567be84b76/sandbox/darwin-sandbox/811/execroot/_main/bazel-out/darwin_x86_64-fastbuild/bin/experimental/service_test_ts_webpack_react_tests/test_/test.runfiles/_main/experimental/service_test_ts_webpack_react_tests/./dist/**/*.spec.js'
    exitCode = await runCommand(
      nodeBin,
      [_mocha_bin, ...mochaArgs],
      process.env,
      _package_dir
    );

    // // To see the command debug message —> open `test.log` files. Example:
    // // $ cat /private/var/tmp/_bazel_tomsoir/828ce2621fc2cfba90cf9c567be84b76/execroot/_main/bazel-out/darwin_x86_64-fastbuild/testlogs/experimental/service_test_ts_webpack_react_tests/test/test.log
    // console.log('>>>>', {commandStr});
  } catch (e) {
    console.error('Tests failed! \n\n\n', e);
  }
  return exitCode;
}

(async function () {
  if (process.env.NODE_ENV !== 'test') {
    let exitCode = await runMochaTests();
    exit(exitCode);
  }
})();
